In [32]:
import numpy as np
import pandas as pd

def generate_data_points(features_count, points_count):
    rnd = np.random.default_rng()

    X = rnd.random((points_count, features_count))
    weights = rnd.random(features_count)
    y = np.random.choice([0, 1], points_count)
    df = pd.DataFrame(X)
    df.columns = [f"x{col}" for col in df.columns]
    df['y'] = y

    bias = 0.5
    return df, weights, bias

df, weights, bias = generate_data_points(features_count = 3, points_count = 2)

print(df)
print(weights)
print(bias)

         x0        x1        x2  y
0  0.950864  0.074868  0.809277  1
1  0.290610  0.372912  0.546745  1
[0.81156129 0.37477091 0.94346405]
0.5
0
x = 
 x0    0.950864
x1    0.074868
x2    0.809277
Name: 0, dtype: float64
weights = 
 [0.81156129 0.37477091 0.94346405]
2.063267060881231
1
x = 
 x0    0.290610
x1    0.372912
x2    0.546745
Name: 1, dtype: float64
weights = 
 [0.81156129 0.37477091 0.94346405]
1.3914387364214793


In [36]:
def get_weighted_sum(X, weights, bias):
    print('x = \n', X)
    print('weights = \n', weights)
    return np.dot(X, weights) + bias

for i in range(len(df)):
    print(f"{i} = ")
    print(get_weighted_sum(df.loc[i][:-1], weights, bias))
    print("---")

0 = 
x = 
 x0    0.950864
x1    0.074868
x2    0.809277
Name: 0, dtype: float64
weights = 
 [0.81156129 0.37477091 0.94346405]
2.063267060881231
---
1 = 
x = 
 x0    0.290610
x1    0.372912
x2    0.546745
Name: 1, dtype: float64
weights = 
 [0.81156129 0.37477091 0.94346405]
1.3914387364214793
---


1.56326651893629